### ISSUE TITLE
[Bug]: 글 작성 시 api 500 에러 발생

### ISSUE THREAD

**Issue by Lim-JiSeon** [prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG#168]
### 무슨 일인가요?

글을 작성하고자 작성 페이지로 이동한 뒤 완료 버튼을 누르면 500 에러가 뜨면서 글을 작성할 수 없습니다.

<img width="1058" alt="스크린샷 2023-09-20 151158" src="https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/83554018/78d80ed9-4ecd-4fb3-a34a-b8f931bf80e7">

<img width="729" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/83554018/543cb424-ff45-4500-bd08-c02a68977f53">

### 어떤 브라우저에서 발생하나요?

Chrome

### 관련 로그 (선택)

```shell
xhr.js:251     POST http://localhost:3000/api/posts/create 500 (Internal Server Error)
```

**Comment by oaoong** [comment]
최신 노드 LTS 버전 (18.18)에서 동작 확인했으므로 이슈를 종료합니다.
