### ISSUE TITLE
[bug]: 닉네임, 프로필 이미지 변경 시 사이드바에 적용안됨

### ISSUE THREAD

**Issue by bomi8489** [prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG#262]
### 해당하는 스토리는 어떤 것인가요?

사용자는 계정 정보 변경 페이지에서 닉네임, 프로필 이미지를 변경할 수 있고, 변경 시 사이드바에 바로 적용된다.

### 무엇에 대한 이슈인가요?

최신 배포 버전에서 닉네임, 프로필 이미지 변경 시 사이드바에 적용되지 않습니다.

**Comment by Lim-JiSeon** [comment]
수정이 된 걸까요? 방금 돌려봤는데 잘 적용이 되어서요..
