### ISSUE TITLE
[Feature]: baseURL 이미지 형태 더 압축해서 담기

### ISSUE THREAD

**Issue by khj0426** [prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG#89]
### 해당하는 스토리는 어떤 것인가요?

새로운 포스트를 작성하고 싶다.

### 무엇에 대한 이슈인가요?

새로운 포스트에 이미지를 첨부한다

**Comment by oaoong** [comment]
필요 없게 됐을지도? 아마 강사님 백엔드에서 알아서 압축될 것 같기도 한데 고화질 이미지로 한 번 테스트 해보겠습니다.
